`sqlite-vec` implementation for vector search
agentlang-ai/agentlang pull request #1622
Opened 2024-12-20 23:35 UTC by muazzam0x48

Uses [sqlite-vec](https://github.com/asg017/sqlite-vec)

2024-12-27 05:07 UTC, vijayfractl requested changes

2024-12-27 05:07 UTC, vijayfractl commented on src/agentlang/inference/embeddings/internal/sqlitevector.clj
> +(defn get-document-classname [app-uuid]
@muazzam0x48 Some of these functions could be shared between all vectdb implementations.

2025-02-07 04:15 UTC, muazzam0x48 commented on src/agentlang/inference/embeddings/internal/sqlitevector.clj
> +(defn get-document-classname [app-uuid]
I have refactored it, please check now

2025-02-07 11:31 UTC, vijayfractl submitted a review, later dismissed

2025-02-08 03:24 UTC, merged